# Shared applications for all hosts
{ pkgs, inputs, ... }:
{
  environment.systemPackages = with pkgs; [
    git
    btrfs-progs
    zotero
    onlyoffice-desktopeditors
    haruna
    pavucontrol
    pwvucontrol
    vesktop
    hardinfo2
    wayland-utils
    kdePackages.plasma-browser-integration
    kdePackages.kcalc
    kdePackages.kcharselect
    kdePackages.kolourpaint
    kdePackages.ksystemlog
    kdePackages.kjournald
    kdePackages.sddm-kcm
    kdePackages.isoimagewriter
    kdePackages.partitionmanager
    catppuccin-kde
    inputs.fenix.packages.${pkgs.stdenv.hostPlatform.system}.complete.toolchain
    lm_sensors
    dmidecode
    google-chrome
    easyeffects
    code-cursor
    todoist
    clinfo
    sshfs
    qbittorrent
    discord
    ghostty
    dnsmasq
    phodav
    usbutils
    obs-studio
    galaxy-buds-client
    xev
    spotify-tray
  ];
}
