{ pkgs, inputs, ... }:
{
  environment.systemPackages = with pkgs; [
    wget
    git
    unzip
    btrfs-progs
    nixfmt
    nixd
    bpftools
    llvm
    clang
    linuxPackages.kernel.dev
    linuxPackages.bpftrace
    typst
    tinymist
    typstyle
    zotero
    onlyoffice-desktopeditors
    haruna
    pavucontrol
    pwvucontrol
    vesktop
    # rustdesk-flutter
    hardinfo2
    lact
    wayland-utils
    wl-clipboard-rs
    kdePackages.plasma-browser-integration
    kdePackages.kcalc
    kdePackages.kcharselect
    kdePackages.kolourpaint
    kdePackages.ksystemlog
    kdePackages.kjournald
    kdePackages.sddm-kcm
    kdePackages.isoimagewriter
    kdePackages.partitionmanager
    kdePackages.xdg-desktop-portal-kde
    catppuccin-kde
    prusa-slicer
    inputs.fenix.packages.${pkgs.stdenv.hostPlatform.system}.complete.toolchain
    lm_sensors
    dmidecode
    # gemini-cli
    # stremio
    google-chrome
    ffmpeg
    # jellyfin-media-player
    easyeffects
    code-cursor
    todoist
    cursor-cli
    radeontop
    dogdns
    sshfs
    unrar
    pspp
    qbittorrent
    discord
    wireguard-tools
    ghostty
    ncdu
    docker-compose
    quickemu
    gnome-boxes
    dnsmasq
    phodav
    usbutils
    obs-studio
  ];
}
