# Shared applications for all hosts
{ pkgs, inputs, ... }:
{
  environment.systemPackages = with pkgs; [
    wget
    git
    unzip
    btrfs-progs
    nixfmt
    nixd
    typst
    tinymist
    typstyle
    zotero
    onlyoffice-desktopeditors
    haruna
    pavucontrol
    pwvucontrol
    vesktop
    hardinfo2
    wayland-utils
    wl-clipboard-rs
    kdePackages.plasma-browser-integration
    kdePackages.kcalc
    kdePackages.kcharselect
    kdePackages.kolourpaint
    kdePackages.ksystemlog
    kdePackages.kjournald
    kdePackages.sddm-kcm
    kdePackages.isoimagewriter
    kdePackages.partitionmanager
    kdePackages.xdg-desktop-portal-kde
    catppuccin-kde
    inputs.fenix.packages.${pkgs.stdenv.hostPlatform.system}.complete.toolchain
    lm_sensors
    dmidecode
    google-chrome
    ffmpeg
    jellyfin-media-player
    easyeffects
    code-cursor
    todoist
    cursor-cli
    clinfo
    doggo
    sshfs
    unrar
    qbittorrent
    discord
    wireguard-tools
    ghostty
    ncdu
    docker-compose
    dnsmasq
    phodav
    usbutils
    obs-studio
    galaxy-buds-client
    yazi
    xev
    gemini-cli
    xwayland-satellite
    spotify
    spotify-tray
  ];
}
